title: 锐毅的博客
email: 2463253700@qq.com
description: >-
  记录一些有趣的事情。

twitter_username: Shuery
github_username: Shuery-Shuai

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

url: "https://blog.shuery.letsshareall.com"

timezone: Asia/Shanghai
encoding: "UTF-8"
